[build]
nixpkgs = ["python311", "gcc", "openssl", "pkg-config", "libffi", "sqlite"]

[install]
cmd = "pip install --upgrade pip && pip install -r requirements.txt"

[start]
cmd = "gunicorn Ecommerce.wsgi --log-file -"
