# Generated by Django 5.2.4 on 2025-09-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('home', 'Home'), ('building', 'Building'), ('device-mobile', 'Mobile'), ('shopping-bag', 'Shopping'), ('car', 'Vehicle'), ('tag', 'Tag'), ('academic-cap', 'Education'), ('heart', 'Health'), ('utensils', 'Food'), ('wrench', 'Services'), ('land', 'Land/Property'), ('electronics', 'Electronics'), ('fashion', 'Fashion')], default='tag', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
