# Generated by Django 5.2.4 on 2025-09-15 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('sell', 'Iibin'), ('rent', 'Kireyn'), ('exchange', 'Isdhaafsi'), ('service', 'Adeeg'), ('job', 'Shaqo'), ('other', 'Kale')], default='sell', max_length=10, verbose_name='Nooca Xayeysiiska'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Xayeysiiyaha'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='area_size',
            field=models.PositiveIntegerField(blank=True, help_text='Tirooyinka oo dhan kaliya (tusaale, 2)', null=True, verbose_name='Cabirka Aagga'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Helitaanka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='camera_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Xallinta Kaamiro'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category', verbose_name='Qaybta'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Midabka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Taariikhda Abuurista'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, verbose_name='Sharaxaad'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='education_required',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Waxbarashada Loo Baahan Yahay'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='electronics_condition',
            field=models.CharField(blank=True, choices=[('new', 'Cusub'), ('second_hand', 'La Isticmaalay')], max_length=20, null=True, verbose_name='Xaaladda Elektaroonigga'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='electronics_type',
            field=models.CharField(blank=True, choices=[('phone', 'Telefoonka Gacanta'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('camera', 'Kaamiro'), ('tv', 'TV'), ('audio', 'Qalabka Maqalka'), ('gaming', 'Kumbuyuutarka Ciyaaraha'), ('smart_home', 'Qalabka Guriga Casriga ah')], max_length=20, null=True, verbose_name='Nooca Elektaroonigga'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='experience_required',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Khuruurta Shaqo ee Loo Baahan Yahay'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='fashion_type',
            field=models.CharField(blank=True, choices=[('men', 'Moodada Ragga'), ('women', 'Moodada Haweenka'), ('kids', 'Moodada Carruurta'), ('watches', 'Saacadaha'), ('jewelry', 'Dahabka'), ('bags', 'Bags & Qalabka')], max_length=20, null=True, verbose_name='Nooca Moodada'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='furnishing_type',
            field=models.CharField(blank=True, choices=[('fully_furnished', 'Si Buuxda loo Qalabeeyay'), ('semi_furnished', 'Qayb ahaan loo Qalabeeyay'), ('unfurnished', 'Aan la Qalabayn')], max_length=20, null=True, verbose_name='Nooca Qalabaynta'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='geartype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nooca Gearka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='has_electricity',
            field=models.BooleanField(default=False, verbose_name='Koronto Ma Leh?'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Baarkin Ma Leh?'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name='Barkad Ma Leh?'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='has_warranty',
            field=models.BooleanField(default=False, verbose_name='Dammaanad Ma Leh?'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='has_water',
            field=models.BooleanField(default=False, verbose_name='Biyo Ma Leh?'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_automatic',
            field=models.BooleanField(default=False, verbose_name='Waa Automatic?'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Waqti Buuxa'), ('part_time', 'Waqti Dhiman'), ('contract', 'Qandaraas'), ('internship', 'Tababar'), ('remote', 'Fogaan')], max_length=20, null=True, verbose_name='Nooca Shaqada'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='land_area',
            field=models.PositiveIntegerField(blank=True, help_text='Tirooyinka oo dhan kaliya (tusaale, 0.5)', null=True, verbose_name='Cabirka Dhulka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='land_type',
            field=models.CharField(blank=True, choices=[('Deegaanka muse', 'Deegaanka'), ('agricultural', 'Beeraha'), ('commercial', 'Ganacsi'), ('industrial', 'Warshadaha')], max_length=20, null=True, verbose_name='Nooca Dhulka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Taariikhda Cusboonaysiinta'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Goobta'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Walxaha'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nooca'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='motortype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nooca Matoorka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Magaca'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='num_baths',
            field=models.PositiveIntegerField(blank=True, help_text='Tirooyinka oo dhan kaliya (tusaale, 2)', null=True, verbose_name='Tirada Musqulaha'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='num_rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Tirooyinka oo dhan kaliya (tusaale, 3)', null=True, verbose_name='Tirada Qolalka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('other', 'Kale')], max_length=20, null=True, verbose_name='Nidaamka Hawlgalka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiimaha'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Processor'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Dhismaha'), ('house', 'Guri'), ('villa', 'Villa'), ('condo', 'Condo'), ('commercial', 'Ganacsi'), ('office', 'Xafiis'), ('warehouse', 'Bakhaar'), ('farmhouse', 'Guriga Beeraha')], max_length=20, null=True, verbose_name='Nooca Hantida'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mushaharka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cabirka shaashadda ee inji', max_digits=5, null=True, verbose_name='Cabirka Shaashadda'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='service_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aagga Adeegga'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='service_type',
            field=models.CharField(blank=True, choices=[('cleaning', 'Nadiifin'), ('moving', 'Rarid & Kaydinta'), ('repair', 'Dayactir & Joogtayn'), ('it', 'Adeegyada IT'), ('beauty', 'Qurux & Fayoobaanta'), ('tutoring', 'Barid & Casharro')], max_length=20, null=True, verbose_name='Nooca Adeegga'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='sim_type',
            field=models.CharField(blank=True, choices=[('single', 'SIM Kaliya'), ('dual', 'Laba SIM'), ('e_sim', 'eSIM')], max_length=20, null=True, verbose_name='Nooca SIM-ka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cabirka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('pending', 'La Sugayo'), ('approved', 'La Ogolaaday'), ('rejected', 'La Diiday')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='ad',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Awoodda Kaydinta'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Baabuur'), ('motorcycle', 'Mooto'), ('bus', 'Bas'), ('truck', 'Gaari Xamuul')], max_length=20, null=True, verbose_name='Nooca Gaariga'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Muuqaalka'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Muddada Dammaanadda'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sanadka'),
        ),
    ]
