# Generated by Django 5.2.4 on 2026-06-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_profile_completed_alter_ad_area_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_completed',
        ),
        migrations.AlterField(
            model_name='ad',
            name='area_size',
            field=models.PositiveIntegerField(blank=True, help_text='Whole numbers only (e.g. 2)', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='land_area',
            field=models.PositiveIntegerField(blank=True, help_text='Whole numbers only (e.g. 0.5)', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='num_baths',
            field=models.PositiveIntegerField(blank=True, help_text='Whole numbers only (e.g. 2)', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='num_rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Whole numbers only (e.g. 3)', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Screen size in inches', max_digits=5, null=True),
        ),
    ]
