# Generated by Django 5.2.4 on 2025-09-15 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_ad_ad_type_alter_ad_advertiser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent'), ('exchange', 'Exchange'), ('service', 'Service'), ('job', 'Job'), ('other', 'Other')], default='sell', max_length=10),
        ),
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ad',
            name='area_size',
            field=models.PositiveIntegerField(blank=True, help_text='Whole numbers only (e.g. 2)', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='camera_resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='education_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='electronics_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('second_hand', 'Second Hand')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='electronics_type',
            field=models.CharField(blank=True, choices=[('phone', 'Mobile Phone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('camera', 'Camera'), ('tv', 'TV'), ('audio', 'Audio Equipment'), ('gaming', 'Gaming Console'), ('smart_home', 'Smart Home Devices')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='experience_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='fashion_type',
            field=models.CharField(blank=True, choices=[('men', "Men's Fashion"), ('women', "Women's Fashion"), ('kids', "Kids' Fashion"), ('watches', 'Watches'), ('jewelry', 'Jewelry'), ('bags', 'Bags & Accessories')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='furnishing_type',
            field=models.CharField(blank=True, choices=[('fully_furnished', 'Fully Furnished'), ('semi_furnished', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='geartype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='has_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='has_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='has_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='land_area',
            field=models.PositiveIntegerField(blank=True, help_text='Whole numbers only (e.g. 0.5)', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='land_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('agricultural', 'Agricultural'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='motortype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='num_baths',
            field=models.PositiveIntegerField(blank=True, help_text='Whole numbers only (e.g. 2)', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='num_rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Whole numbers only (e.g. 3)', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ad',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('condo', 'Condo'), ('commercial', 'Commercial'), ('office', 'Office Space'), ('warehouse', 'Warehouse'), ('farmhouse', 'Farm House')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ram',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Screen size in inches', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='service_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='service_type',
            field=models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('moving', 'Moving & Storage'), ('repair', 'Repair & Maintenance'), ('it', 'IT Services'), ('beauty', 'Beauty & Wellness'), ('tutoring', 'Tutoring & Lessons')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='sim_type',
            field=models.CharField(blank=True, choices=[('single', 'Single SIM'), ('dual', 'Dual SIM'), ('e_sim', 'eSIM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='ad',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('truck', 'Truck')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
