# Generated by Django 5.2.4 on 2026-06-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_profile_completed_alter_ad_area_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(default=1, upload_to='ad_images/'),
            preserve_default=False,
        ),
    ]
