# Generated by Django 5.2.4 on 2025-09-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('Property', 'Property'), ('Lands', 'Lands'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Vehicles', 'Vehicles'), ('Services', 'Services'), ('Jobs', 'Jobs'), ('Beauty & Salons', 'Beauty & Salons'), ('Decoration', 'Decoration')], default='tag', max_length=20),
        ),
    ]
