# Generated by Django 5.2.4 on 2025-09-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('building', 'Property'), ('land', 'Lands'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('car', 'Vehicles'), ('wrench', 'Services'), ('briefcase', 'Jobs'), ('scissors', 'Beauty & Salons'), ('paint-brush', 'Decoration')], default='tag', max_length=20),
        ),
    ]
