# Generated by Django 5.2.4 on 2025-10-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_sellerstats_sellerrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerstats',
            options={'verbose_name_plural': 'Seller Stats'},
        ),
        migrations.AddField(
            model_name='sellerrating',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='base.ad'),
        ),
        migrations.AddField(
            model_name='sellerrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sellerstats',
            name='five_star_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerstats',
            name='four_star_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerstats',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sellerstats',
            name='one_star_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerstats',
            name='three_star_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerstats',
            name='two_star_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerrating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')]),
        ),
        migrations.AddIndex(
            model_name='sellerrating',
            index=models.Index(fields=['seller', 'created_at'], name='base_seller_seller__e4e9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerrating',
            index=models.Index(fields=['rater', 'created_at'], name='base_seller_rater_i_7ec69d_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerstats',
            index=models.Index(fields=['average_rating', 'total_ratings'], name='base_seller_average_15f958_idx'),
        ),
    ]
