# Generated by Django 5.2.4 on 2025-10-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_notification_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval', 'Ad Approved'), ('rejection', 'Ad Rejected'), ('featured', 'Ad Featured'), ('info', 'Information'), ('warning', 'Warning')], max_length=20),
        ),
    ]
