# Generated by Django 5.2.4 on 2025-10-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_notification_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='base.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval', 'Ad Approved'), ('rejection', 'Ad Rejected'), ('featured', 'Ad Featured'), ('info', 'Information'), ('warning', 'Warning'), ('comment', 'New Comment'), ('reply', 'New Reply')], max_length=20),
        ),
    ]
